import type { Metadata } from "next";
import "@/app/globals.css"; // Gunakan alias untuk impor global CSS
import Navbar from "@/app/Components/Navbar"; // Gunakan alias untuk impor Navbar
import Footer from "@/app/Components/Footer"; // Gunakan alias untuk impor Footer
import FloatingButtons from "@/app/Components/FloatingButtons"; // Gunakan alias untuk FloatingButtons

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Navbar */}
        <Navbar />

        {/* Konten Halaman */}
        <main>{children}</main>

        {/* Footer */}
        <Footer />

        {/* Floating Buttons */}
        <FloatingButtons />
      </body>
    </html>
  );
}
